#view resolver 
spring:
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula
 messages:
  basename: com/nt/validation/validations
#hibernate properties
 jpa:
  database-platform: org.hibernate.dialect.OracleDialect
  show-sql: true
  hibernate: 
   ddl-auto: update
   
#server port Number
server:
 port: 4108
#context path
 servlet:
  context-path: /software_solution
    

