
#jdbc properties
spring: 
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula
 jpa:
  database-platform: org.hibernate.dialect.OracleDialect
  show-sql: true
  hibernate:
   ddl-auto: update
#server port number
server:
 port: 4118
#applicationContext path
 servlet:
  context-path: /pdf_excel_document
  
