#View resolver
spring:
 mvc: 
  view:
   prefix: /WEB-INF/pages/
   suffix: .jsp
#oracle properties
 datasource:
  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: siva
  password: velpula
#hibernate properties
 jpa:
  database-platform: org.hibernate.dialect.OracleDialect
  show-sql: true
  hibernate:
   ddl-auto: update
  
server:
 port: 4114
 servlet:
  context-path: /init_binder_ldt

